# Generated by Django 2.2.4 on 2019-08-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190828_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/placeholder.png', upload_to='images/'),
        ),
    ]
