# Generated by Django 2.2.4 on 2019-08-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190830_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/placeholder.png', upload_to='media'),
        ),
    ]
