# Generated by Django 2.2.4 on 2019-08-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190830_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/images/placeholder.png', upload_to='media'),
        ),
    ]
