# Generated by Django 2.2.4 on 2019-08-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190828_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/images/placeholder.png', upload_to='images'),
        ),
    ]
