# Generated by Django 2.2.4 on 2019-08-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20190830_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/Users/kama/Documents/CODE/MY_APPS/Django--Diary/static/images/placeholder.png', upload_to='images'),
        ),
    ]
